jobs:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install pywavelets
        - pip install pytest
        - python setup.py install
  # - "pypy3"  # currently Python 3.6.1
      script: pytest -v tests/*.py

    - language: python
      python:
        - "3.8"
      install:
        - pip install pywavelets
        - pip install pytest
        - python setup.py install
      script: pytest -v tests/*.py

    - name: codecov
      language: python
      install:
        - pip install pytest-cov codecov
        - pip install pywavelets pytest 
      script: 
        - py.test tests/*.py  --cov-report term --cov=optimusprimal --collect-only 
      # Push the results back to codecov
      after_success:
        - codecov
    
