jobs:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install pywavelets
        - pip install pytest
  # - "pypy3"  # currently Python 3.6.1
      script: pytest -v op_tests.py prox_tests.py

    - language: python
      python:
        - "3.8"
      install:
        - pip install pywavelets
        - pip install pytest
      script: pytest -v tests/*.py

    - name: codecov
      language: python
      install:
        - pip install pytest-cov codecov
        - pip install pywavelets pytest 
      script: 
        - py.test  --cov-report term --cov=optimusprimal
      # Push the results back to codecov
      after_success:
        - codecov
    
