# command to run tests
# command to install dependencies
install:
  - pip install pywavelets
  - pip install pytest
  # - "pypy3"  # currently Python 3.6.1
jobs:
  include:
    - language: python
      python:
        - "3.6"
      script: pytest -v op_tests.py prox_tests.py

    - language: python
      python:
        - "3.8"
      script: pytest -v op_tests.py prox_tests.py

    - name: codecov
      language: python
      install:
        - pip install pytest-cov
      script: pytest --cov=./
      # Push the results back to codecov
      after_success:
        - codecov
    
